### ISSUE TITLE
Update the "Config file for production"-section in README

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/Howitz#109]
The "Config file for production"-section must be checked against the actual prod config file in order to find out whether there are gaps in this section that should be filled and/or some variables that should be described.

I have so far found the following gap in the "Config file for production"-section:
- when setting ``[howitz] -> devmode`` to `false`, the app does not run since Flask's `listen` (address) and `port` values are not provided. The (separate) "Run in production"-section refers to flask's docs in order to help configuring the flask app. **But**: one - some info in the "Run in production"- and the "Config file for production"-section belongs together yet it is spread across the `README`; two - referring to Flask docs does not necessarily help with correctly placing the flask related config values in the Howitz' config file.
- ... more?

**Comment by hmpf** [comment]
Which is the production config file?

**Comment by hmpf** [comment]
I was referring to the two toml-files included in the source. But no matter, I'll update the readme.
