### ISSUE TITLE
Refactor after changes in zinolib

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/Howitz#24]
- [ ] remove direct usage of Adapters (fixed in Uninett/zinolib#18)
- [ ] fix zino session handling as mentioned by @hmpf in #18 (after Uninett/zinolib#22 and Uninett/zinolib#25 are merged)

**Comment by hmpf** [comment]
HistoryAdapter.add can be replaced with manager.add_history_entry_for_id.

EventAdapter.set_admin_state can be replaced with manager.change_admin_state_for_id.
