### ISSUE TITLE
Check that Zino 2 behaves the same as Zino 1 when setting the same state twice in a row on the same event

### ISSUE THREAD

**Issue by hmpf** [Uninett/Howitz#52]
Old zino apparently doesn't set the same state twice in a row.

We'll have to check what zino2 does when we start testing: does it behave similarly? If not, it should, or we might have to fix the redundancy ourselves, in zinolib.

**Comment by lunkwill42** [comment]
So, what you're saying is that in Zino1 allows you to do arbitrarily many `SETSTATE` operations to the same value on the same case, but will only log actual value changes:

```
> setstate 166588 ignore
< 200 ok
> setstate 166588 ignore
< 200 ok
> gethist 166588
< history follows, terminated with '.'
< 1706267986 state change embryonic -> open (monitor)
< 1706269037 state change open -> ignore (mvold)
< .
```

**Comment by lunkwill42** [comment]
I can confirm Zino 2 works in the same way.
